# Generated by Django 5.2.11 on 2026-02-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
