# Generated by Django 5.2.11 on 2026-02-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0002_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
