# Generated by Django 5.2.4 on 2026-02-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0003_alter_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pay_until',
            field=models.DateField(blank=True, null=True, verbose_name="To'lov muddati"),
        ),
    ]
