# Generated by Django 5.2.4 on 2026-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0004_student_pay_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason_type',
            field=models.CharField(blank=True, choices=[('sababli', 'Sababli'), ('sababsiz', 'Sababsiz')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
